---
apiVersion: v2
name: tgp-operator
description: Kubernetes operator for ephemeral Talos Linux GPU provisioning across
  multiple cloud providers
type: application
version: 0.0.1
appVersion: 0.0.1
home: https://github.com/solanyn/tgp-operator
sources: [https://github.com/solanyn/tgp-operator]
maintainers:
  - name: '@solanyn'
    email: 14799876+solanyn@users.noreply.github.com
