[tools]
golang = "1.25.1"
kubectl = "1.34.0"
helm = "3.18.6"
node = "22.19.0"
"npm:@apiture/openapi-down-convert" = "latest"
op = "latest"
python = "latest"
svu = "latest"
"pipx:yamlfix" = "latest"
setup-envtest = "latest"
git-chglog = "latest"
actionlint = "latest"
golangci-lint = "latest"
gofumpt = "latest"
trivy = "latest"
kubeconform = "latest"

[env]
GOBIN = "{{config_root}}/bin"
