providers:
  vultr:
    enabled: true
    credentialsRef:
      name: tgp-operator-secret
      key: VULTR_API_KEY
  gcp:
    enabled: true
    credentialsRef:
      name: tgp-operator-secret
      key: GOOGLE_APPLICATION_CREDENTIALS_JSON
talos:
  image: ghcr.io/siderolabs/talos:v1.10.6
tailscale:
  tags:
    - "tag:k8s"
    - "tag:cloud"
  ephemeral: true
  acceptRoutes: true
  oauthCredentialsRef:
    name: tgp-operator-secret
    clientIdKey: client-id
    clientSecretKey: client-secret
